---
# reboot a server

- hosts: localhost
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
  - name: "update: Rebooting ..."
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
